# Site settings
title: "jatin's dev notes"
email: "jatinkrmalik@gmail.com"
description: >-
  Raw technical explorations and dev notes from a Principal Engineer. 
  Unpolished thoughts on distributed systems, cloud architecture, 
  home lab experiments, and everything in between.
baseurl: ""
url: "https://jatinkrmalik.github.io" # Change this to your GitHub Pages URL
author: "@jatinkrmalik"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages safe gems
safe: true
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  posts:
    output: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Remove pagination for now (not essential for initial setup)

# SEO settings
social:
  name: "Jatin K Malik"
  links:
    - https://j47.in
    - https://www.linkedin.com/in/jatinkrmalik/
    - https://jatinkrmalik.com
    - https://github.com/jatinkrmalik

# Theme settings
theme_color: "#00ff00"
background_color: "#000000" 